<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-IL4H1CC" failures="3" tests="3" name="BankingApp(failed)" time="36.234" errors="0" timestamp="2023-03-22T00:16:17 IST">
  <testcase classname="in.corecreditv1.testcases.TC_LoginDDT_002" name="loginDDT" time="8.482">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at in.corecreditv1.testcases.TC_LoginDDT_002.loginDDT(TC_LoginDDT_002.java:31)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- loginDDT -->
  <testcase classname="in.corecreditv1.testcases.TC_LoginDDT_002" name="loginDDT" time="7.484">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at in.corecreditv1.testcases.TC_LoginDDT_002.loginDDT(TC_LoginDDT_002.java:31)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- loginDDT -->
  <testcase classname="in.corecreditv1.testcases.TC_LoginDDT_002" name="loginDDT" time="6.908">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at in.corecreditv1.testcases.TC_LoginDDT_002.loginDDT(TC_LoginDDT_002.java:31)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- loginDDT -->
</testsuite> <!-- BankingApp(failed) -->
